server:
  port: 8189
  servlet:
    context-path: /app
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver
    hikari:
      hikari:
        maximum-pool-size: 10
    jpa:
      database: postgresql
      database-platform: org.hibernate.dialect.PostgreSQL10Dialect
      show-sql: true
      hibernate:
        ddl-auto: validate
